---

- hosts: all
  gather_facts: no
  remote_user: administrator
  become: true

  tasks:
    - name: Remove rpm file in /opt/
      ansible.builtin.shell: rm -rf /opt/*.rpm
      args:
        executable: /bin/bash

    - name: copying folder new version r7_office.rpm to remote host
      ansible.builtin.copy:
        src: /etc/ansible/roles/redos-7.3.4-install-soft/files/soft/r7_office/r7-office-2024.4.1-630.el8.x86_64.rpm
        dest: /opt

    - name: update r7 office
      ansible.builtin.shell: dnf update -y /opt/r7-office-2024.4.1-630.el8.x86_64.rpm
      args:
        executable: /bin/bash

