---

- hosts: all
  gather_facts: no
  remote_user: administrator
  become: true

  tasks:
    - name: Remove rpm file in /opt/
      ansible.builtin.shell: rm -rf /opt/*.rpm
      args:
        executable: /bin/bash

    - name: Remove the kyocera drivers package
      ansible.builtin.dnf:
        name: kyodialog
        state: absent
        autoremove: yes

    - name: copying folder new version kyocera drivers
      ansible.builtin.copy:
        src: /etc/ansible/roles/redos-7.3.4-install-soft/files/soft/kyocera_drivers/kyodialog-9.4-0.x86_64.rpm
        dest: /opt

    - name: update kyocera drivers
      ansible.builtin.shell: dnf install -y /opt/kyodialog-9.4-0.x86_64.rpm
      args:
        executable: /bin/bash

    - name: Remove rpm file in /opt/
      ansible.builtin.shell: rm -rf /opt/*.rpm
      args:
        executable: /bin/bash

