---
# handlers file for redos-7.3.4-install-soft
- name: disabling systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    state: stopped
    enabled: false

- name: enabling systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    state: started
    enabled: true

- name: enable autostart and restart ntp service
  ansible.builtin.shell: systemctl enable systemd-timesyncd.service && systemctl restart systemd-timesyncd.service
  args:
    executable: /bin/bash

- name: disable automatic mapping of printers
  ansible.builtin.shell: systemctl disable avahi-daemon && systemctl stop avahi-daemon
  args:
    executable: /bin/bash

- name: x11 daemon-reload-enable-start
  ansible.builtin.shell: systemctl daemon-reload && systemctl enable x11vnc.service && systemctl start x11vnc.service
  args:
    executable: /bin/bash
