---
# tasks file for redos-7.3.4-install-soft
- name: disable kernel updates
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    line: exclude=kernel*

- name: dnf update and upgrade the system
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Copying an input script to a domain
  ansible.builtin.copy:
    src: files/scripts/domain/join-to-domain-redos.sh
    dest: /opt/scripts/
    mode: +x

- name: install soft
  ansible.builtin.dnf:
    name:
      - smbpass
      - perl-Getopt-Long
      - perl-File-Copy
      - x11vnc
      - gvfs
      - evolution
      - evolution-ews
      - linphone
      - python3-chardet
      - htop
    state: latest

- name: remove ntp
  ansible.builtin.dnf:
    name: ntp
    state: absent
    autoremove : yes

  notify:
    - disabling systemd-timesyncd

- name: set timezone to Asia/Krasnoyarsk
  community.general.timezone:
    name: Asia/Krasnoyarsk

- name: echo ntp to /etc/systemd/timesyncd.conf
  ansible.builtin.lineinfile:
    path: /etc/systemd/timesyncd.conf
    line: NTP=10.37.11.71

  notify:
    - enabling systemd-timesyncd

- name: Turning "set-ntp" on
  command: /usr/bin/timedatectl set-ntp on

  notify:
    - enable autostart and restart ntp service

- name: install "ifcplugin-chromium.x86_64" for gosuslugi
  ansible.builtin.dnf:
    name: ifcplugin-chromium.x86_64
    state: present

- name: install "librecad-2.1.3-53.16.el7.x86_64"
  ansible.builtin.dnf:
    name: librecad-2.1.3-53.16.el7.x86_64
    state: present

- name: install "librecad-langs-2.2.0-0.11.rc2.el7.noarch"
  ansible.builtin.dnf:
    name: librecad-langs-2.2.0-0.11.rc2.el7.noarch
    state: present

- name: copying folder soft to remote host
  ansible.builtin.copy:
    src: files/soft/
    dest: /opt/soft

- name: install kontur plugin
  ansible.builtin.shell: dnf install -y /opt/soft/kontur/kontur.plugin.002061.rpm
  args:
    executable: /bin/bash

- name: install 1c client 8.3.22
  ansible.builtin.shell: dnf install -y /opt/soft/1c/1c-enterprise-8.3.22.2239-thin-client-8.3.22-2239.x86_64.rpm
  args:
    executable: /bin/bash

- name: install 1c client 8.3.24.1586
  ansible.builtin.shell: dnf install -y /opt/soft/1c/1c-enterprise-8.3.24.1586-thin-client-8.3.24-1586.x86_64.rpm
  args:
    executable: /bin/bash

- name: shell command for 1c client 8.3.24.1586
  ansible.builtin.shell: mv /opt/1cv8/common/libstdc++.so.6 /opt/1cv8/common/libstdc++.so.6.old && ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /opt/1cv8/common/libstdc++.so.6 && mv /opt/1cv8/x86_64/8.3.24.1586/libstdc++.so.6 /opt/1cv8/x86_64/8.3.24.1586/libstdc++.so.6.old && ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /opt/1cv8/x86_64/8.3.24.1586/libstdc++.so.6
  args:
    executable: /bin/bash

- name: install r7 office
  ansible.builtin.shell: dnf install -y /opt/soft/r7_office/r7-office-2024.3.2-551.el8.x86_64.rpm
  args:
    executable: /bin/bash

- name: install epel-release
  ansible.builtin.shell: dnf install -y /opt/soft/epel-release/epel-release-latest-7.noarch.rpm
  args:
    executable: /bin/bash

- name: install kyocera drivers
  ansible.builtin.shell: dnf install -y /opt/soft/kyocera_drivers/kyodialog-9.3-0.x86_64.rpm
  args:
    executable: /bin/bash

- name: install katusha m348 drivers
  ansible.builtin.shell: dnf install -y /opt/soft/katusha_drivers/katusha-m348-ps-1.3.2.x86_64.rpm
  args:
    executable: /bin/bash

- name: install pdf master
  ansible.builtin.shell: dnf install -y /opt/soft/pdf/master-pdf-editor-5.9.84-qt5.x86_64.rpm
  args:
    executable: /bin/bash

  notify:
    - disable automatic mapping of printers

- name: Copy libjcPKCS11-2.so file to /usr/lib64/
  ansible.builtin.copy:
    src: /opt/soft/IUS/libjcPKCS11-2.so
    dest: /usr/lib64/
    remote_src: true
    owner: root
    group: root
    mode: '777'

- name: create password file for x11vnc
  ansible.builtin.shell: x11vnc -storepasswd {{ vncpass }} /etc/vncpasswd
  args:
    executable: /bin/bash

- name: create service file for x11vnc
  template:
    src=templates/x11vnc.service
    dest=/lib/systemd/system/
  notify:
    - x11 daemon-reload-enable-start

- name: filling desktop file for department
  template:
    src=templates/department.desktop
    dest=/etc/xdg/autostart/

- name: filling desktop file for info
  template:
    src=templates/info.desktop
    dest=/etc/xdg/autostart/

- name: filling desktop file for share
  template:
    src=templates/share.desktop
    dest=/etc/xdg/autostart/

- name: filling desktop file for reconnect share
  template:
    src=templates/reconnect-share.desktop
    dest=/usr/share/applications/

- name: copy recoonect-share icon file
  ansible.builtin.copy:
    src: files/scripts/reconnect-share/reconnect-share.png
    dest: /usr/bin/
    owner: root
    group: root
    mode: u+rwx,g+rwx,o+rwx

- name: copy reconnect-share shell file
  ansible.builtin.copy:
    src: files/scripts/reconnect-share/reconnect-share.sh
    dest: /usr/bin/
    owner: root
    group: root
    mode: u+rwx,g+rwx,o+rwx

- name: creating a desktop file intranet-portal-gazprom.desktop
  template:
    src=templates/intranet-portal-gazprom.desktop
    dest=/usr/share/applications/

- name: creating a desktop file phonebook-gdk.desktop
  template:
    src=templates/phonebook-gdk.desktop
    dest=/usr/share/applications/

- name: creating a desktop file phonebook-pao-gazprom.desktop
  template:
    src=templates/phonebook-pao-gazprom.desktop
    dest=/usr/share/applications/

- name: creating a desktop file portal-gdk.desktop
  template:
    src=templates/portal-gdk.desktop
    dest=/usr/share/applications/

- name: creating a desktop file consultant.desktop
  template:
    src=templates/consultant.desktop
    dest=/usr/share/applications/
